name = "satomatashikiookura"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "satomatashikiookura"
database_id = "7a7b52ec-3c90-4889-ab13-873322372383"
